target-version = "py310"
line-length = 100

[lint]
select = ["E","F","W","I","UP","B","SIM","PIE","RUF"]
ignore = [
  "E501",   # long lines (weâ€™ll allow 100 via line-length)
]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
